apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-app-1-config-map
data:
  CRASH_ON_BOOT: {{ if .Values.crash_on_boot }}"1"{{else}}""{{end}}
  CRASH_ON_RENDER: {{ if .Values.crash_on_render }}"1"{{else}}""{{end}}
  EXTRA: {{ .Values.message | quote }}
