apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: static
  name: static
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - image: gcr.io/sandbox-20200610-98rxvk/static:2
        imagePullPolicy: IfNotPresent
        name: static
      dnsPolicy: ClusterFirst
      restartPolicy: Always
